package com.location.voicetest.db.green;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.location.voicetest.dbbean.TestInfo;
import com.location.voicetest.dbbean.UserInfo;

import com.location.voicetest.db.green.TestInfoDao;
import com.location.voicetest.db.green.UserInfoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig testInfoDaoConfig;
    private final DaoConfig userInfoDaoConfig;

    private final TestInfoDao testInfoDao;
    private final UserInfoDao userInfoDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        testInfoDaoConfig = daoConfigMap.get(TestInfoDao.class).clone();
        testInfoDaoConfig.initIdentityScope(type);

        userInfoDaoConfig = daoConfigMap.get(UserInfoDao.class).clone();
        userInfoDaoConfig.initIdentityScope(type);

        testInfoDao = new TestInfoDao(testInfoDaoConfig, this);
        userInfoDao = new UserInfoDao(userInfoDaoConfig, this);

        registerDao(TestInfo.class, testInfoDao);
        registerDao(UserInfo.class, userInfoDao);
    }
    
    public void clear() {
        testInfoDaoConfig.clearIdentityScope();
        userInfoDaoConfig.clearIdentityScope();
    }

    public TestInfoDao getTestInfoDao() {
        return testInfoDao;
    }

    public UserInfoDao getUserInfoDao() {
        return userInfoDao;
    }

}
